-- HD Machine Monitoring - PostgreSQL schema
-- Jalankan satu kali pada database PostgreSQL Railway yang masih kosong.
-- Script ini hanya membuat tabel dan index. Tidak ada data demo yang dimasukkan.

BEGIN;

CREATE TABLE IF NOT EXISTS machines (
    machine_id VARCHAR(50) PRIMARY KEY,
    status VARCHAR(20) NOT NULL DEFAULT 'stopped',
    last_update TIMESTAMP WITHOUT TIME ZONE,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    total_active_time DOUBLE PRECISION NOT NULL DEFAULT 0,
    current_session_start TIMESTAMP WITHOUT TIME ZONE,
    last_heartbeat TIMESTAMP WITHOUT TIME ZONE,
    completed_treatments INTEGER NOT NULL DEFAULT 0,
    pump_status VARCHAR(20) NOT NULL DEFAULT 'stopped',
    pump_last_heartbeat TIMESTAMP WITHOUT TIME ZONE,
    dialysis_session_start TIMESTAMP WITHOUT TIME ZONE,
    total_dialysis_time DOUBLE PRECISION NOT NULL DEFAULT 0,
    completed_dialysis INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    assigned_regions JSON NOT NULL DEFAULT '[]'::json,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS machine_metadata (
    machine_id VARCHAR(50) PRIMARY KEY
        REFERENCES machines(machine_id),
    serial_number VARCHAR(50) NOT NULL,
    hospital_name VARCHAR(100) NOT NULL,
    unit_number INTEGER NOT NULL,
    region VARCHAR(50) NOT NULL,
    subregion VARCHAR(50) NOT NULL,
    category VARCHAR(10) NOT NULL,
    installation_date DATE,
    registered_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    archived_at TIMESTAMP WITHOUT TIME ZONE,
    archived_by INTEGER REFERENCES users(id),
    archive_note TEXT
);

CREATE TABLE IF NOT EXISTS errors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id VARCHAR(50) REFERENCES machines(machine_id),
    error_code VARCHAR(20),
    type VARCHAR(50),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    server_received_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS maintenance_config (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    threshold_type VARCHAR(20) NOT NULL,
    threshold_value INTEGER NOT NULL,
    time_unit VARCHAR(10),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS maintenance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id VARCHAR(50) REFERENCES machines(machine_id),
    item VARCHAR(50) NOT NULL,
    dialysis_count INTEGER NOT NULL DEFAULT 0,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT NOT NULL,
    performed_by INTEGER REFERENCES users(id),
    serial_number_snapshot VARCHAR(50) NOT NULL,
    item_name_snapshot VARCHAR(100) NOT NULL,
    performed_by_snapshot VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS humidity_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id VARCHAR(50) REFERENCES machines(machine_id),
    humidity DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS voltage_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id VARCHAR(50) REFERENCES machines(machine_id),
    event_type VARCHAR(20) NOT NULL,
    voltage DOUBLE PRECISION,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index berikut mempercepat filter dashboard dan pencarian data terbaru.
CREATE INDEX IF NOT EXISTS idx_metadata_region_subregion
    ON machine_metadata (region, subregion);

CREATE INDEX IF NOT EXISTS idx_metadata_archive_region_subregion
    ON machine_metadata (is_archived, region, subregion);

CREATE INDEX IF NOT EXISTS idx_errors_machine_received
    ON errors (machine_id, server_received_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_maintenance_machine_item_time
    ON maintenance (machine_id, item, timestamp DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_maintenance_history_time
    ON maintenance (timestamp DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_maintenance_config_active_name
    ON maintenance_config (active, name);

CREATE INDEX IF NOT EXISTS idx_humidity_machine_time
    ON humidity_logs (machine_id, timestamp DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_voltage_machine_event_time
    ON voltage_events (machine_id, event_type, timestamp DESC, id DESC);

COMMIT;
